apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kata
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: prod
      path: 'k8s/kata'
  destination:
    server: https://kubernetes.default.svc
    namespace: kata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true